 name: Docker Series Builds

 
 on: [push]

 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
       
       
     - name: docker login
       env:
         DOCKER_USER: ${{ secrets.DOCKER_USER }}   
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
       run: |
         sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
       
     - name: docker build csharp
       run: |
         docker build ./c# -t a84136757/csharp:1.0.0
     - name: docker build nodejs
       run: |
         docker build ./nodejs -t a84136757/nodejs:1.0.0
     - name: docker build python
       run: |
         docker build ./python -t a84136757/python:1.0.0
     - name: docker build golang
       run: |
         docker build ./golang -t a84136757/golang:1.0.0
     - name: docker push
       run: |
          sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
          sudo chmod g+rwx "/home/$USER/.docker" -R
          docker push a84136757/csharp:1.0.0
          docker push a84136757/nodejs:1.0.0
          docker push a84136757/python:1.0.0
          docker push a84136757/golang:1.0.0
